# Generated by Django 4.0.5 on 2022-07-02 16:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employee_register', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='addTrip',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('transporter_name', models.CharField(blank=True, max_length=100, null=True)),
                ('vehicle', models.CharField(blank=True, max_length=100)),
                ('source', models.CharField(blank=True, choices=[('DILPURA', 'DILPURA'), ('BANAR', 'BANAR'), ('NAURANGPUR', 'NAURANGPUR')], max_length=50, null=True)),
                ('destination', models.CharField(blank=True, choices=[('JAIPUR', 'JAIPUR'), ('AHEMADABAD', 'AHMEDABAD'), ('DELHI', 'DELHI')], max_length=50, null=True)),
                ('approx_distance', models.PositiveIntegerField(blank=True, null=True)),
                ('Fixed_amount_btw_s_d', models.PositiveIntegerField(default=100)),
                ('is_active', models.BooleanField(default=True)),
            ],
        ),
    ]
